apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadnuxb8065-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadnuxb8065-tenant-component
    app.kubernetes.io/part-of: loadnuxb8065-tenant-app
  name: loadnuxb8065-tenant-component
  namespace: loadnuxb8065-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadnuxb8065-tenant-component
    weight: null
status: {}
